agent:
  name: redis-tier0-agent
  version: 0.1

connection:
  timeout_seconds: 2

environments:
  dev:
    type: non-prod
    hosts: 
      - ip: 192.168.17.145
        redis:
          mode: standalone
          ports:
            - 6379

  #qa:
    #hosts: [qa-redis-01]
  #uat:
  # hosts: [uat-redis-01, uat-redis-02, uat-redis-03]
  #staging:
  # hosts: [stage-redis-01]
  #prod:
  #  type: prod
  #  hosts:
  #  - ip: 10.0.1.10
  #     redis:
  #       mode: cluster
  #       ports: [6379, 6380]

  #  - ip: 10.0.1.11
  #      redis:
  #        mode: cluster
  #        ports: [6379, 6380]

  #  - ip: 10.0.1.12
  #      redis:
  #        mode: cluster
  #        ports: [6379, 6380]

reporting:
  output: reports/latest.md
  min_severity_to_report: medium
